### PR TITLE
feat!: parameter object is null object

### PR DESCRIPTION
**Pull request by Uzlopak**
see https://github.com/fastify/fastify/issues/4357

@eomm
@mcollina
@jsumners

I did not bench

### CODE REVIEW

**Comment by Uzlopak** [comment]
tests fail because of tap issues...

**Comment by Uzlopak** [comment]
Need to benchmark.

**Review by mcollina — COMMENTED** [review]
I think this shoukd be a semver-major change.

**Comment by Uzlopak** [comment]
@climba03003 

It seems that new NullObject is faster than using __proto__ trick

```sh
node benchmark/null-object.js 
new NullObject() x 1,377,691,231 ops/sec ±0.11% (194 runs sampled)
{__proto__: null } x 33,097,458 ops/sec ±0.50% (185 runs sampled)
```

```js
'use strict'

const { NullObject } = require('../lib/null-object')

const Benchmark = require('benchmark')
Benchmark.options.minSamples = 100

const suite = Benchmark.Suite()

suite.add(`new NullObject()`, function () {
  const result = new NullObject()
})
suite.add(`{__proto__: null }`, function () {
  const result = {__proto__: null }
})
suite
  .on('cycle', function (event) {
    console.log(String(event.target))
  })
  .on('complete', function () {
  })
  .run()

```

**Comment by mcollina** [comment]
Can you exclude windows v14 from CI?

**Comment by Uzlopak** [comment]
@mcollina done.

I would like to write another benchmark for the actual parameter generation. So please dont merge to fast.

I posted my benchmark to discuss if __proto__ is the right way or not.

**Review by mcollina — APPROVED** [review]
lgtm looks nice!

**Comment by mcollina** [comment]
PTAL @ivan-tymoshenko

**Review by ivan-tymoshenko — APPROVED** [review]
lgtm

**Comment by ivan-tymoshenko** [comment]
@Uzlopak Can you post the bechmarks comparison pls?

**Review by gurgunday — APPROVED** [review]

**Comment by mcollina** [comment]
can you merge main?

**Review by climba03003 — APPROVED** [review]
We all missed this one.
cc @mcollina

**Review by mcollina — APPROVED** [review]
lgtm

**Review by Eomm — COMMENTED** [review]
LGTM

I have no power here - @Uzlopak could you edit the title with `feat!: ...` to stand out the breaking?

**Comment by Uzlopak** [comment]
@Eomm 

Donr

**Pull request merged**
