### PR TITLE
Fix constrainer overwrite

### LINKED ISSUE #254: `constraints` will be overrided when multiple router created
The current code override the `HandlerStorage.prototype.constrainer` to get the `constrainter` in router.
It will be override when two store created first before any route trying to lookup.

```js
const findMyWay = require("find-my-way");

const constraint = {
  name: "secret",
  storage: function () {
    let secrets = {};
    return {
      get: (secret) => {
        return secrets[secret] || null;
      },
      set: (secret, store) => {
        secrets[secret] = store;
      },
      del: (secret) => {
        delete secrets[secret];
      },
      empty: () => {
        secrets = {};
      },
    };
  },
  deriveConstraint: (req, ctx) => {
    return req.headers["x-secret"];
  },
  validate() {
    return true;
  },
};

let router1 = findMyWay({ constraints: { secret: constraint } });

// it override the constraints of router1
const router2 = findMyWay({ constraints: undefined });

// it can registered constraints
router1.on("GET", "/", { constraints: { secret: "alpha" } }, () => {});
// it cannot find the constraints secret
router1.find("GET", "/", { constraints: { secret: "alpha" } });
```

### PR DESCRIPTION
**Pull request by bugagashenkj**
Fixed #254

### CODE REVIEW

**Review by climba03003 — COMMENTED** [review]
I will change the order of argument.
`constrainer` comes first then the other options.

It is more consistence in my eyes and `storage` usually not going to be removed / changed, but options depends on it will.

**Comment by bugagashenkj** [comment]
I changed the order

**Review by climba03003 — APPROVED** [review]
Nice

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
