### PR TITLE
feat: add multiple parametric nodes support

### LINKED ISSUE #317: Allow users to have an additional regex node
find-my-way has a [caveat](https://github.com/delvedor/find-my-way#caveats): it can't have two different routes which differ only for their parameters. What we can allow users to have is a regular parametrical node and a regexp node (or multi-parametrical node, which is also a regexp node), in case there is only one regex node. In this case, we know that the regex node has higher priority than the regular one.

Example:
- `/foo/:param1`
- `/foo/:param2.png`

@mcollina @Eomm @Uzlopak @RafaelGSS @climba03003 WDYT?

### PR DESCRIPTION
**Pull request by ivan-tymoshenko**
Close #317

### CODE REVIEW

**Review by mcollina — COMMENTED** [review]
does this affects our benchmarks?

**Comment by ivan-tymoshenko** [comment]
No, all changes are in the compile time.

**Comment by ivan-tymoshenko** [comment]
This PR is ready to review. It allows you to have two identical routes with different param types: general parameter and regexp parameter.

Example:
- `/foo/:param`
- `/foo/:param(123)`

Code in the `index.js` is pretty tricky. I don't ask you to review it unless you have a lot of time to deal with it. Please take a look at two things:

1. Params [sorting function](https://github.com/delvedor/find-my-way/pull/320/files#diff-8370cfb1d23c8a7441ac8b34e2c5cca7ced2bc7bf84365b3dc6da8bd01d11f14R78). It describes how we would prioritese parametric nodes. (param node with long suffix -> param node with short suffix -> regexp node -> param node without suffix)

2. Please look at the test file. It more or less describes all params collisions and priorities. It's pretty simple and readable.

If you have any suggestions, you are more than welcome. 

cc @mcollina @climba03003 @Eomm

**Review by mcollina — CHANGES_REQUESTED** [review]
Can you add some docs for this?

**Review by climba03003 — COMMENTED** [review]
Can we defer the sorting to certain point later?
For example, once the first call of `lookup`.

It seems to do a lot of unnecessary sorting when there are many routes.

**Comment by ivan-tymoshenko** [comment]
> Can we defer the sorting to certain point later? For example, once the first call of `lookup`.
> 
> It seems to do a lot of unnecessary sorting when there are many routes.

Technically we can, you are right. But you will have this sorting in a very small amount of cases. You a sorting parametric childs of _one_ parent node. IMHO, in 99% of all use cases, you have one parametric child, and in 1%, you have two children: general and regexp. All other cases are less than the statistical error.

On the other hand, this will complicate the already complicated code and introduce an additional error in measuring the hot path. I would agree with you 100% if it would make any difference, but you will not notice it.

**Comment by climba03003** [comment]
> You a sorting parametric childs of one parent node. IMHO, in 99% of all use cases, you have one parametric child, and in 1%, you have two children. All other cases are less than the statistical error.

At least we can do `if(this.parametricChildren.length > 1)` to prevent single item array being sorted.

**Comment by ivan-tymoshenko** [comment]
> At least we can do if(this.parametricChildren.length > 1) to prevent single item array being sorted.

I think that the sort function is smart enough to not call a sorting handler for an array with one item. But I can add this, not a problem at all.

**Review by delvedor — APPROVED** [review]
LGTM with some docs!

**Comment by climba03003** [comment]
> > At least we can do if(this.parametricChildren.length > 1) to prevent single item array being sorted.
> 
> I think that the sort function is smart enough to not call a sorting handler for an array with one item. But I can add this, not a problem at all.

nvm, it is actually smart enough to skip the run.

```js
function sorter(a, b) {
  console.log('did run')
  return a - b
}

;['a'].sort(sorter)
;['a', 'b'].sort(sorter)
```

**Review by climba03003 — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
