### PR TITLE
Bumped dependencies

### PR DESCRIPTION
**Pull request by davisjam**
Upgrade to the hot-off-the-press safe-regex v2.0.0.

### CODE REVIEW

**Comment by davisjam** [comment]
Sorry, haven't yet published this package due to weird npm misconfiguration on my end.

Will update the PR soon.

**Comment by davisjam** [comment]
PR updated. Let's see how Travis-CI does.

**Comment by mcollina** [comment]
what’s the main difference with the new version?

**Comment by davisjam** [comment]
1. Switches from `ret` to `regexp-tree` to build a regex AST. I didn't notice any differences in the test suite (or in the test suites of a few dependencies) but it is possible that some regexes may no longer be parse-able and some others may be newly parse-able.
2. Fixes a class of false negatives for which star height was incorrectly calculated. For example regexes like `(a*|b)*` -- see [substack's safe-regex #8](https://github.com/substack/safe-regex/issues/8).

**Comment by mcollina** [comment]
CI fails on Node v4. Can you just remove it from travis.yml? This is semver/major anyway.

**Comment by davisjam** [comment]
Done.

**Comment by delvedor** [comment]
Done in v2, thanks for letting us know!

**Pull request closed without merging**
