### PR TITLE
Use http methods

### PR DESCRIPTION
**Pull request by allevo**
As titled

### CODE REVIEW

**Comment by delvedor** [comment]
You should also update this code:
https://github.com/delvedor/find-my-way/blob/cc6ac4e5a1b1617ca2d84cce33201f727ae12c8b/node.js#L129-L140

Same for the shorthand api.
And maybe add some test.

**Comment by allevo** [comment]
I haven't added shorthand api because some methods conflict with the existent API like `find`.

**Comment by delvedor** [comment]
> Let me know if I have to add them

Yes please, an half complete API is not that good, even if is a simple thing :)

**Comment by allevo** [comment]
done. Changed README too

**Pull request merged**
