### PR TITLE
Optimize constraints' strategies

### PR DESCRIPTION
**Pull request by bugagashenkj**
I optimized the version constraint strategy and removed empty and delete methods from the strategy interface. I don't know why we need them.

### CODE REVIEW

**Comment by bugagashenkj** [comment]
**Main branch**

main

**Current branch**

current

**Review by mcollina — COMMENTED** [review]
This is a semver-major change

**Comment by bugagashenkj** [comment]
@mcollina Why do you think so? I just removed unused methods.

**Review by RafaelGSS — APPROVED** [review]
Impressive results in constrained routes. LGTM.

**Review by mcollina — APPROVED** [review]
lgtm, those methods are not really exposed!

**Pull request merged**
