### PR TITLE
Optimize find method

### PR DESCRIPTION
**Pull request by bugagashenkj**
I refactored the find method. The main things that were changed:
- removed double path/prefix checking (in the find and findMatchingChild methods)
- removed unnecessary path splitting, I replaced it on just path pointer
- a bunch of other small optimizations

### CODE REVIEW

**Comment by bugagashenkj** [comment]
depends on #224

**Comment by bugagashenkj** [comment]
### Benchmark results:
**Before:**

Снимок экрана 2021-12-21 в 22 54 48

**After:**

image

**Comment by bugagashenkj** [comment]
There is one thing that worries me. If someone can explain under what conditions this code can be executed, I will be very grateful. Because I think that this is an unreachable path of the code and tests also don't cover it.

https://github.com/delvedor/find-my-way/blob/9207236eb9a434293180c581c43bf7adcda1ee9d/index.js#L508

**Comment by mcollina** [comment]
Good job!!!!

**Review by mcollina — APPROVED** [review]
lgtm

**Review by delvedor — COMMENTED** [review]
Heya! The changes looks good, but I would like to take a little more time to review them! I'm currently on PTO, I'll take a look as soon as I'm back :)

**Review by delvedor — APPROVED** [review]
Great work!

**Pull request merged**
