### PR TITLE
refactor: move sanitizeUrl() to find(); remove from lookup())

### PR DESCRIPTION
**Pull request by spasquali-ww**
Referencing: https://github.com/delvedor/find-my-way/issues/162#issue-695999569

### CODE REVIEW

**Comment by Eomm** [comment]
Could you add some test to cover your issue and avoid regressions in future?

**Review by delvedor — CHANGES_REQUESTED** [review]
Hello! This behavior is intended.
`find` should only look if something has been stored under that path.
The reason behind it is because you can also use find my way as a store for something else than routes, and sanitizing might be a problem.
`lookup` is the api for working with http.

**Comment by spasquali-ww** [comment]
Aha. Please close this then. Sorry for the confusion!

Intrigued about using `find()` for storing other 'things'...

**Comment by delvedor** [comment]
Thank you for contributing!

Yeah, the fourth parameter in a route declaration is a store object, where you can put anything you like and you can retrieve it with `find`.
Ma his is also how we are handling the context of each route in Fastify :)

**Pull request closed without merging**
