### PR TITLE
add dependabot.yml

### PR DESCRIPTION
**Pull request by Uzlopak**
Well. why are we not keeping our deps up to date?

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
Can you also add the action that automatically land the PRs if they pass the tests? We have it in Fastify.

**Comment by Uzlopak** [comment]
@mcollina 

done

**Comment by Uzlopak** [comment]
@mcollina 

Whazzup? Not good enough?

**Comment by mcollina** [comment]
CI is failing

**Comment by Uzlopak** [comment]
@mcollina 
I dont think it was my PRs fault as it is not related to the macos runners. probably github had some issues. Can you retrigger them? Also: Do we need a GITHUB_TOKEN in secrets?

**Comment by Uzlopak** [comment]
@mcollina 

sry, stupid bug from my side

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
