### PR TITLE
Made the validate function of the ContraintStrategy in the typescript…

### PR DESCRIPTION
**Pull request by nickwinger**
… definition optional (as it is also optional in the js-code) added the validate function in the readme doc

### CODE REVIEW

**Review by ivan-tymoshenko — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
Can you please add an assertion/example in https://github.com/delvedor/find-my-way/blob/main/test/types/router.test-d.ts? So we don't regress.

**Comment by nickwinger** [comment]
> Can you please add an assertion/example in https://github.com/delvedor/find-my-way/blob/main/test/types/router.test-d.ts? So we don't regress.

ok, i made another commit

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
