### PR TITLE
Fix host constraints not working when http2 is enabled

### PR DESCRIPTION
**Pull request by anker2000**
Find-my-way is relying on req.headers.host to determine the host, however when http2 is enabled req.headers.host won't return the host name. For http2 req.headers[':authority'] could be used.

### CODE REVIEW

**Comment by Eomm** [comment]
Could you add unit tests and revert the `package.json` changes?
We will take care of the version

**Comment by anker2000** [comment]
I've updated the package.json file (sorry - forgot to clean that up), but this is my first ever pull request, and I unfortunately have no idea what a unit test is.

**Comment by mcollina** [comment]
https://github.com/delvedor/find-my-way/blob/36e1888a8158cc030e0ab586064d828f5aa8e00f/test/server.test.js < this file test a lot of things for http. You should create one for http2.

**Comment by mcollina** [comment]
Can you rebase? There are spurious commits.

**Pull request closed without merging**
