### PR TITLE
Run benchmarks in separate threads

### LINKED ISSUE #232: Benchmark results depend on their order
There is something wrong happening with benchmarks. What I can say now is if you reorder your test cases you can get different results. I can't tell right now why it's happening, there can be myriads of reasons. I wanna start with the most extreme case: the first test case executes much faster than others. I was trying to test it on my laptop and my PC and got the same results. That's why I think that the "/" route executes much faster than others #225 (it's still a unique case, but the difference is not so dramatic). I was looking through the issues/PRs where people send their benchmarks and sometimes I saw the same picture (https://github.com/delvedor/find-my-way/pull/176#issuecomment-759957811). If you have the ability, please make some tests regarding the first test case. You can create multiple same tests and see if there are any differences depending on the test's place or just switch some tests and see if there is any difference.

### PR DESCRIPTION
**Pull request by bugagashenkj**
Fixed #232

### CODE REVIEW

**Review by delvedor — COMMENTED** [review]
Nice job! @mcollina any thoughts?

**Comment by bugagashenkj** [comment]
### Benchmark results:
**Main branch:**

main

**Current branch:**

threads

**Current branch (shuffled):**

Снимок экрана 2022-01-12 в 23 12 59

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
This code is quite good!

**Comment by bugagashenkj** [comment]
@delvedor I've found two duplicate benchmarks. Are they duplicates indeed or there should be some differences between them?

### **First:**
https://github.com/delvedor/find-my-way/blob/5beaacfcb6d1bb53663a90b5e7f0d5e9540e15ce/bench.js#L107
https://github.com/delvedor/find-my-way/blob/5beaacfcb6d1bb53663a90b5e7f0d5e9540e15ce/bench.js#L119

### **Second:**
https://github.com/delvedor/find-my-way/blob/5beaacfcb6d1bb53663a90b5e7f0d5e9540e15ce/bench.js#L116
https://github.com/delvedor/find-my-way/blob/5beaacfcb6d1bb53663a90b5e7f0d5e9540e15ce/bench.js#L122

**Pull request merged**
