### PR TITLE
Enable versioning on demand

### PR DESCRIPTION
**Pull request by delvedor**
This pull request disables the automatic route versioning unless a user has configured at least once a route with the version option.

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by airhorns** [comment]
Could you maybe add a little more context as to why this was necessary? I think the constraints implementation has to change to support this but I can't really tell how.

**Comment by airhorns** [comment]
ping @mcollina @delvedor would love to know why this change was necessary

**Comment by mcollina** [comment]
It's a security vulnerability, see https://snyk.io/vuln/SNYK-JS-FINDMYWAY-1038269 for more details.

**Pull request merged**
