### PR TITLE
feat: replace querystring with fast-querystring

### PR DESCRIPTION
**Pull request by anonrig**
Solves issue: https://github.com/fastify/fastify/issues/4252

### CODE REVIEW

**Comment by anonrig** [comment]
@delvedor I added all of the node.js querystring tests and released a new version (0.3.0) with the necessary changes to replicate the behavior of the `node:querystring` package.

**Review by ivan-tymoshenko — APPROVED** [review]
LGTM! Update the doc, please.

**Comment by anonrig** [comment]
@ivan-tymoshenko I just updated `fast-querystring` module to 0.3.1 which comes with **~7%** faster parsing and updated the README.

**Comment by anonrig** [comment]
Updated to 0.4.0 with lots of great improvements.

**Comment by Fdawgs** [comment]
This repo supports node >=14, but `fast-querystring` uses `replaceAll()`, which requires Node >=15.

**Comment by mcollina** [comment]
This will likely land in a major version, ideally shipping February/March 2023, in which we will drop support for Node v14 and v16. 

(v16 LTS ends Sept 2023 due to OpenSSL).

**Comment by anonrig** [comment]
I might replace `replaceAll` with `replace` if that is a deal breaker. The performance difference is acceptable since even without it, the package is quite fast. @Fdawgs

**Comment by anonrig** [comment]
FYI: Updated this pull-request to 0.7.0 (40% faster than querystring atm), dropped replaceAll in favor of supporting Node 14.

**Review by mcollina — APPROVED** [review]
lgtm, I think this would be a significant benefit for the project.

**Review by RafaelGSS — APPROVED** [review]
LGTM. Good job!

**Comment by anonrig** [comment]
I released and updated the pull request to use 1.0.0 version. I think `fast-querystring` is stable.

**Review by delvedor — APPROVED** [review]
LGTM

**Comment by mcollina** [comment]
@delvedor should I cut a major?

**Comment by ivan-tymoshenko** [comment]
@mcollina @delvedor Can you explain to me why we should land it as a major? It's not a breaking change. It's not even a new feature. It might have a good querystring performance parsing upgrade, but it will not make a significant performance difference along with routing. And we have the 7.1.0 version now.  Why can't we land it as a 7.2.0?

**Comment by mcollina** [comment]
I'm ok with a minor too.

**Comment by anonrig** [comment]
If we are ok with this pull request, can we merge & release @mcollina @delvedor?

**Comment by delvedor** [comment]
> Can you explain to me why we should land it as a major? 

The main reason is that this module has an average of 3.6 millions downloads per months, and you don't want to risk it :D
If we are confident there are no hidden breaking changes, we can do a minor.

**Comment by mcollina** [comment]
I'll try a minor and in case revert

**Pull request merged**
