### PR TITLE
Fixed parameters parsing

### LINKED ISSUE #235: Issue in parameter resolution
Hi, 

I m using my find-my-way via Fastify and I m facing an issue parametrics url. 

I defined a route like that : `GET /images/:id.jpg`
When I make this request `GET /images/123456.jpg` it works as expected but when I make this one :  `GET /images/12346-fr.jpg`
It's does not work.

I think the issue is linked  to the support of multi params

### PR DESCRIPTION
**Pull request by bugagashenkj**
Fixed #235 #238

The main problem with multi-parametrical nodes is that we can't easily describe the rules of how should it be parsed. Thanks for @mcollina, he said that if I have an unclear case it should work as the [path-to-regexp](https://github.com/pillarjs/path-to-regexp) library does https://github.com/delvedor/find-my-way/issues/238#issuecomment-1021464532. The path-to-regexp converts the hole path to the regexp, so a multi-parametric path is also parsed as a regex. The main idea of this solution is to convert the multi-parametrical part of the path to the regexp. Seems like it's the only way to make it work properly.

**Important point: It doesn't convert the whole path to the regexp (as path-to-regexp does), only the part of the path between two '/' if it contains multiple params or param and static part.**

It replaces parameters with (.*?), regex parameters with themselves, the static part is also inserted into the regex.

Examples:
| Description | Multi-parametrical part of path  | Regexp | 
|---|---|---|
| Param with static part | /:param1-static/ | /^(.*?)-static$/ | 
| Multiple params | /:param1-:param2/ | /^(.\*?)-(.\*?)$/ | 
| Regexp param with param | /:param1(^\\w{3}).param2/ | /^(\w{3})\\.(.\*?)$/  | 

Depends on #243

### CODE REVIEW

**Review by mcollina — COMMENTED** [review]
Could you run the benchmarks before and after?

**Comment by bugagashenkj** [comment]
**Main branch**

Снимок экрана 2022-03-31 в 14 00 51

**Current branch**

Current

**Comment by bugagashenkj** [comment]
Yep, I can explain it. There is a regression for a multi-parameter route because previously two parametric nodes were used to parse paths like that `/:param1-:param2/`, which did not contain any regular expressions. It just parsed everything before and after the "-" as parameters. But there wasn't the right behavior. It worked only with simple paths. Now when it uses regex for this it obviously takes more time, but it works correctly in general.

About "multi-parametric route with regexp". It created two different nodes to parse paths like that `/:param1(^\w{3}).param2/`. The first is a param node with regex and the second is just a parametric node. Now it's just one regex parametric node. I guess that is the reason why it's working faster.

**Review by mcollina — APPROVED** [review]
lgtm

**Review by delvedor — APPROVED** [review]

**Pull request merged**
